export default {
  type: "object",
  properties: {
    name: { type: "string" },
    price: { type: "number" },
    category: { type: "string" },
    deliveryDuration: { type: "string" },
    deliveryUnit: { type: "string" },
    quantityValue: { type: "string" },
    quantityUnit: { type: "string" },
    description: { type: "string" },
    deliveryActive: { type: "boolean" },
    qtyLeft: { type: "number" },
    qtySold: { type: "number" },
    visibility: { type: "boolean" },
    productID: { type: "string" },
    images: { type: "object" },
    storeID: { type: "string" },
  },
  required: [
    "name",
    "price",
    "category",
    "description",
    "productID",
    "images",
    "storeID",
  ],
  additionalProperties: false,
};
