export default {
  type: "object",
  properties: {
    storeID: { type: "string" },
    storeName: { type: "string" },
    phoneNumber: { type: "string" },
    email: { type: "string", format: "email" },
    facebook: { type: "string" },
    twitter: { type: "string" },
    instagram: { type: "string" },
    whatsapp: { type: "string" },
    walletBalance: { type: "number" },
    bankAccount: { type: "number" },
    bankName: { type: "string" },
    sellerName: { type: "string" },
    plan: { type: "string" },
    storeLink: { type: "string" },
  },
  required: [
    "storeID",
    "storeName",
    "phoneNumber",
    "email",
    "bankAccount",
    "bankName",
    "sellerName",
    "plan",
    "storeLink",
  ],
  additionalProperties: false,
};
